;NAME:P.PADMAJA PATRA
;REGD NO.-2141016197
;OBJ2:ARRANGE THE ELEMENTS OF A GIVEN ARRAY OF SIZE 'N' IN ASCENDING ORDER
.DATA
COUNT DB 04H
VALUE DB 03H,02H,04H,01H
.CODE
MAIN PROC
   MOV AX,DATA
   MOV DS,AX
   MOV CL,COUNT
   DEC CL
UP2:MOV CH,CL
   LEA SI,VALUE
UP1:MOV AL,[SI]
   CMP AL,[SI+1]
   JC DWN 
   MOV DL,[SI+1]
   XCHG [SI],DL
   MOV [SI+1],DL
DWN:INC SI
   DEC CH
   JNZ UP1
   DEC CL
   JNZ UP2
END MAIN    