;NAME:P.PADMAJA PATRA
;REGD NO.-2141016197
;OBJ1:LARGEST AMONG 'N' NUMBERS USING ASSEMBLER DIRECTIVE OR ARRAY
.DATA
COUNT DB 04H
VALUE DB 0FH,09H,14H,10H
RES DB 0
.CODE
MAIN PROC
MOV AX,DATA
MOV DS,AX
MOV CL,COUNT
DEC CL
LEA SI,VALUE
MOV AL,[SI]
UP:INC SI
CMP AL,[SI]
JNC DWN
MOV AL,[SI]
DWN:DEC CL
JNZ UP
LEA DI,RES
MOV [DI],AL
END MAIN    