;NAME:P.PADMAJA PATRA
;REGD NO.: 2141016197
;OBJ3:SWAPPING OF NIBBLE OF DATA1,Y=(DATA1 AND DATA2) OR (DATA1 XOR DATA2)

MOV AX,1000H
MOV DS,AX
MOV SI,5000H
MOV AL,[SI]
INC SI   
MOV BL,[SI] 
MOV CL,AL
ROR CL,04H
INC SI            
MOV [SI],CL            

MOV CL,AL
AND CL,BL 
MOV DL,AL
XOR DL,BL
OR CL,DL      
INC SI
MOV [SI],CL
HLT
MOV AL,[5000H]
MOV CL,AL
SHR CL,01H
XOR AL,CL
MOV [5001H],AL    
HLT